Development
MouhaDiouf/thenextweb_replica pull request #1
Opened 2019-06-24 09:32 UTC by MouhaDiouf

2019-06-24 12:27 UTC, Torres-ssf requested changes

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +                    <div class="article1">
Should be an `article` tag instead.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +                            <div class="article2">
Should be an `article` tag instead.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +                            <div class="article3">
Should be an `article` tag instead.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +        <div class="latest-news">
Should be a `section` tag instead.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +        <div class="latest-funding">
Should be a `section` tag instead.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +                    <div class="latest-news-thumbnail">
This should be an `article` tag instead. Each one of the 8 latest news articles must be inside an `article` tag. Kindly do that with them all.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +                <div class="subjectwell">
This should be an article tag instead. Each one of the 3 latest funding articles must be inside an article tag. Kindly do that with them all.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +        <div class="group1">
This should be a `section` tag instead.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +            <div class="apps group-item">
This should be a `section` tag instead. Each one of the 8 sections (apps, gear, tech, creative, podium...) must be inside a section tag. Kindly do that with them all.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +              <div class="apps-image">
This should be an article tag instead. Each one of the 8 within articles must be inside an article tag (even the elements inside the `li` tag. Kindly do that with them all.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +              <div class="related">
This should be an article tag instead.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +                   <li><a href="#">YouTube will soon let you try out makeup with AR</a></li>
The anchor tag must be inside an `article` tag. Kindly do that with all list elements.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +            <div class="latest-deals-text">
Should be inside a `section` instead.

2019-06-24 12:27 UTC, Torres-ssf commented on index.html
> +            <div class="latest-deals-thumbnail">
Each one of the 8 articles must be inside an `article` tag instead. kindly do that with all of them.

2019-06-24 12:31 UTC, Torres-ssf commented
Hi there @MouhaDiouf @emmanuelkamala. You guys did a really good work on this project 👏. But before I give 👍, we need to do some change to make it match Microverse guidelines. I did a series of reviews in your code. After making these changes, it will be in accord with Microverse's guidelines.

2019-06-25 21:54 UTC, bellom commented
Hi @MouhaDiouf @emmanuelkamala,
can you please fix the validation errors.

2019-06-25 23:00 UTC, bellom approved these changes
Hi @MouhaDiouf @emmanuelkamala,
You guys have done great, i trust you guys are going to fix the validation errors.
Go ahead and merge after fixing the errors
Goodluck in the next project :+1:

2019-06-26 18:40 UTC, MouhaDiouf commented
Thank you!

Le mar. 25 juin 2019 à 23:00, Oluwaseun Bello <notifications@github.com> a
écrit :

> *@bellom* approved this pull request.
>
> Hi @MouhaDiouf <https://github.com/MouhaDiouf> @emmanuelkamala
> <https://github.com/emmanuelkamala>,
> You guys have done great, i trust you guys are going to fix the validation
> errors.
> Go ahead and merge after fixing the errors
> Goodluck in the next project 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MouhaDiouf/thenextweb_replica/pull/1?email_source=notifications&email_token=AIU2CHJVFOQSLUVSMZUJVDTP4KPPJA5CNFSM4H24YOXKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB4UH5MI#pullrequestreview-254312113>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIU2CHMZLRL5JKGN35I5BWTP4KPPJANCNFSM4H24YOXA>
> .
>

2019-06-27 09:41 UTC, merged